image: ghcr.io/astral-sh/uv:python3.13-alpine

variables:
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - .uv-cache

before_script:
  - python3 -V # Print out python version for debugging
  - uv --version # Print out uv version for debugging
  - mkdir -p .uv-cache
  - export UV_CACHE_DIR=.uv-cache
  - uv sync --frozen

build:
  stage: build
  script:
    - uv run python app.py
