language: python
python:
  - "3.13"
install:
  - curl -LsSf https://astral.sh/uv/install.sh | sh
  - source $HOME/.local/bin/env
  - uv sync
script:
  - uv run pytest
  - uv run pytest --cov=./
after_success:
  - uv run codecov # It uses the CODECOV_TOKEN environment variable
